version: '3.7'
services:
  redis:
    image: redis:5-buster
    restart: on-failure
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - listing

  db:
    image: mysql:8.0.22
    container_name: legion-movie-mysql
    volumes:
      - docker-mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode=""
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: LegionMovie
      MYSQL_USER: user
      MYSQL_PASSWORD: hello

volumes:
  docker-mysql:
    driver: local

networks:
  listing:
    driver: bridge
